### ISSUE TITLE
PyPi package contains bogus 'seeder' source files

### ISSUE THREAD

**Issue by gpseconsulting** [ricekab/sqlalchemy-seeder#11]
Here's the content of the .whl file currently in PyPi at sqlalchemy_seeder-0.3.0-py2.py3-none-any.whl:

> $ unzip sqlalchemy_seeder-0.3.0-py2.py3-none-any.whl

> Archive:  sqlalchemy_seeder-0.3.0-py2.py3-none-any.whl
>   **inflating: seeder/\_\_init__.py**
>   **inflating: seeder/basic_seeder.py**
>  **inflating: seeder/exceptions.py**
>  **inflating: seeder/resolving_seeder.py**
>  **inflating: seeder/resources/resolver.schema.json**
>   inflating: sqlalchemyseeder/\_\_init__.py
>   inflating: sqlalchemyseeder/basic_seeder.py
>   inflating: sqlalchemyseeder/exceptions.py
>   inflating: sqlalchemyseeder/resolving_seeder.py
>   inflating: sqlalchemyseeder/resources/resolver.schema.json
>   inflating: sqlalchemy_seeder-0.3.0.dist-info/DESCRIPTION.rst
>   inflating: sqlalchemy_seeder-0.3.0.dist-info/metadata.json
>   inflating: sqlalchemy_seeder-0.3.0.dist-info/top_level.txt
>   inflating: sqlalchemy_seeder-0.3.0.dist-info/WHEEL
>   inflating: sqlalchemy_seeder-0.3.0.dist-info/METADATA
>   inflating: sqlalchemy_seeder-0.3.0.dist-info/RECORD`

Note how it contains both 'seeder' and 'sqlalchemyseeder'. The former contains what appears to be broken/outdated code while the latter works as expected. 

I figured this out after troubleshooting this error message

> AttributeError: 'dict_values' object has no attribute 'append'

I was importing the wrong package ('seeder') based on usage.rst which references that one. I created https://github.com/ricekab/sqlalchemy-seeder/pull/10 to get that fixed.

**Comment by ricekab** [comment]
Fixed in pr #10 . Docs will be updated on RTD later today as there is no automation for this currently.
