### ISSUE TITLE
Getting AttributeError: No registered class found for 'services.models.core.State'

### ISSUE THREAD

**Issue by lanshark** [RiceKab/sqlalchemy-seeder#9]
Situation:  We have several model classes, defined in services/models/core.py, services/models/authentication.py, etc.  In services/models/__init__.py, we import all of those classes, so we can just do from services.models import xxx where xxx is any model defined in any of the underlying classes.

So, for example, if I have a State model, defined in services/models/core.py, I would import it as:
"from services.models import State", which works just fine.

when trying to load a fixture, however, I'm getting the above error no matter what I put in the json file:
{
    "target_class": "services.models.State",
   
or
{ 
    "target_class": "services.models.core.State", 

both give the error above.  Am I missing something?
Do I need to register the classes myself somewhere before trying to load_from_json_file()?
The doc's are not real clear.

**Comment by lanshark** [comment]
Never Mind -- figured it out... D'OH!

**Comment by RiceKab** [comment]
I can see how it's confusing given that the documentation examples are actually wrong (the text above the example is actually correct). I'll add this to the documentation enhancement.

**Comment by philipokiokio** [comment]
Hi, I have a question about this. 

So I am currently facing the same issue. 

"target_class": "src.store: Cart"

This is similar to the documentation, however, I get the Value Error, Class not found in the module.


Plus the Model lives in models script.
